name: pomodoro_app
description: A new Flutter project.


publish_to: 'none' 



environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  pausable_timer: ^1.0.0+6
  sleek_circular_slider: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true
